import { SENSITIVE } from "./fixtures"

/**
 * Messages built by hand, byte by byte.
 *
 * Not generated by a library: the point of most of these is a shape a
 * well-behaved library would never produce — a boundary written without its
 * closing delimiter, a header folded across three lines, an address split by
 * an entity in the HTML alternative, a forwarded message four levels down. A
 * fixture that can only be built by a correct MIME writer tests the happy path
 * twice and nothing else.
 *
 * CRLF throughout, because that is what messages use, and a parser that only
 * works on LF works on nothing that arrived over SMTP.
 */

export const EML = {
  person: SENSITIVE.person,
  email: SENSITIVE.email,
  phone: SENSITIVE.phone,
  colleague: "Jane Doe",
  colleagueEmail: "jane@example.com",
  accented: "Zoé Müller",
  accentedEmail: "zoe@example.com",
} as const

function message(lines: string[]): string {
  return lines.join("\r\n")
}

export function bytesOf(source: string): Uint8Array {
  return new Uint8Array(Buffer.from(source, "latin1"))
}

/** The ordinary case: headers and one plain-text body. */
export function simpleEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    `To: ${EML.colleague} <${EML.colleagueEmail}>`,
    "Subject: Quarterly review",
    "Date: Mon, 3 Mar 2026 09:14:02 +0000",
    "Message-ID: <abc123@mail.example.com>",
    "MIME-Version: 1.0",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `Hello ${EML.colleague},`,
    "",
    `You can reach me on ${EML.phone} or at ${EML.email}.`,
    "",
    `-- ${EML.person}`,
    "",
  ])
}

/** The same content twice, as text and as HTML. */
export function alternativeEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    `To: <${EML.colleagueEmail}>`,
    "Subject: With an HTML alternative",
    "MIME-Version: 1.0",
    'Content-Type: multipart/alternative; boundary="alt-boundary"',
    "",
    "--alt-boundary",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `Call ${EML.person} on ${EML.phone}.`,
    "",
    "--alt-boundary",
    'Content-Type: text/html; charset="utf-8"',
    "",
    "<html><body>",
    // The address is split by a tag and written partly as an entity, and it
    // also sits in an href that never appears on screen. Three ways for a
    // string search over the markup to find nothing.
    `<p>Call <b>${EML.person}</b> on ${EML.phone}.</p>`,
    `<p>Mail <a href="mailto:${EML.email}">jo<span>hn</span>&#64;example.com</a></p>`,
    "</body></html>",
    "",
    "--alt-boundary--",
    "",
  ])
}

/**
 * An HTML body with the structure a reviewer actually needs.
 *
 * Wrapped in the nested single-cell layout tables every newsletter is built
 * from, so the extraction has to tell those apart from the one table that
 * really is a table.
 */
export function richHtmlEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    `To: <${EML.colleagueEmail}>`,
    "Subject: Quarterly review",
    "MIME-Version: 1.0",
    'Content-Type: text/html; charset="utf-8"',
    "",
    "<html><body>",
    '<table width="600"><tr><td>',
    "  <table><tr><td>",
    "    <h1>Quarterly review</h1>",
    "    <p>Attendees, in",
    "    reading order:</p>",
    `    <ul><li>${EML.colleague}</li><li>Bob Chen</li></ul>`,
    "    <table>",
    "      <tr><th>Name</th><th>Role</th></tr>",
    `      <tr><td>${EML.person}</td><td>Chair</td></tr>`,
    "    </table>",
    `    <p>Mail <a href="mailto:${EML.email}">the chair</a>.</p>`,
    "    <blockquote><p>On Tue, Bob wrote:</p></blockquote>",
    "  </td></tr></table>",
    "</td></tr></table>",
    "</body></html>",
    "",
  ])
}

/** Text, an HTML alternative, and a binary attachment with a telling name. */
export function mixedEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    `To: <${EML.colleagueEmail}>`,
    "Subject: Your documents",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="outer"',
    "",
    "--outer",
    'Content-Type: multipart/alternative; boundary="inner"',
    "",
    "--inner",
    'Content-Type: text/plain; charset="utf-8"',
    "Content-Transfer-Encoding: quoted-printable",
    "",
    `Attached is the review for ${EML.person}.=20`,
    "",
    "--inner",
    'Content-Type: text/html; charset="utf-8"',
    "",
    `<p>Attached is the review for ${EML.person}.</p>`,
    "",
    "--inner--",
    "",
    "--outer",
    "Content-Type: application/pdf",
    'Content-Disposition: attachment; filename="2026-review-John Smith.pdf"',
    "Content-Transfer-Encoding: base64",
    "",
    // Enough of a PDF header to be sniffed as one, which is the point: this
    // is what an attachment that becomes a document of its own looks like.
    // The suites that call redactEml without a substitution plan still get it
    // back byte-identical, because carrying through is what happens when
    // nothing says otherwise.
    "JVBERi0xLjQKJSBhIHNtYWxsIGZpeHR1cmUgcGF5bG9hZAo=",
    "",
    "--outer--",
    "",
  ])
}

/** A reply quoting the message it answers, which quotes another. */
export function quotedReplyEml(): string {
  return message([
    `From: ${EML.colleague} <${EML.colleagueEmail}>`,
    `To: ${EML.person} <${EML.email}>`,
    "Subject: Re: Quarterly review",
    `In-Reply-To: <abc123@mail.example.com>`,
    `References: <abc123@mail.example.com> <def456@mail.example.com>`,
    "MIME-Version: 1.0",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    "Thanks, that works.",
    "",
    `On Mon, 3 Mar 2026, ${EML.person} <${EML.email}> wrote:`,
    `> You can reach me on ${EML.phone} or at ${EML.email}.`,
    `> -- ${EML.person}`,
    ">",
    `>> Earlier still, ${EML.person} wrote:`,
    `>> My number is ${EML.phone}.`,
    "",
  ])
}

/** A message carrying another message, which carries a third. */
export function nestedEml(): string {
  return message([
    "From: Mail Delivery <postmaster@example.com>",
    `To: ${EML.colleagueEmail}`,
    "Subject: Fwd: Quarterly review",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="fwd"',
    "",
    "--fwd",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    "Forwarding the message below.",
    "",
    "--fwd",
    "Content-Type: message/rfc822",
    "",
    `From: ${EML.person} <${EML.email}>`,
    `To: ${EML.colleagueEmail}`,
    "Subject: Quarterly review",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="inner-fwd"',
    "",
    "--inner-fwd",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `My direct line is ${EML.phone}.`,
    "",
    "--inner-fwd",
    "Content-Type: message/rfc822",
    "",
    `From: ${EML.person} <${EML.email}>`,
    "Subject: The original",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `Three deep, still ${EML.email}.`,
    "",
    "--inner-fwd--",
    "",
    "--fwd--",
    "",
  ])
}

/** Encoded words, a folded header, and UTF-8 in a display name. */
export function encodedHeaderEml(): string {
  const subject = Buffer.from(`Rapport de ${EML.accented}`, "utf8").toString(
    "base64"
  )
  const displayName = Buffer.from(EML.accented, "utf8").toString("base64")

  return message([
    `From: =?utf-8?B?${displayName}?= <${EML.accentedEmail}>`,
    `To: ${EML.colleagueEmail}`,
    `Subject: =?utf-8?B?${subject}?=`,
    // Folded across three lines, which is what a long recipient list does.
    `Cc: ${EML.email},`,
    `  ${EML.colleagueEmail},`,
    `  someone.else@example.com`,
    "MIME-Version: 1.0",
    'Content-Type: text/plain; charset="utf-8"',
    "Content-Transfer-Encoding: base64",
    "",
    Buffer.from(
      `Bonjour, je suis ${EML.accented}. Mon email est ${EML.accentedEmail}.\r\n`,
      "utf8"
    ).toString("base64"),
    "",
  ])
}

/** The same address in six different places. */
export function duplicatedEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    `Reply-To: ${EML.email}`,
    `To: ${EML.colleagueEmail}`,
    `Return-Path: <${EML.email}>`,
    `Received: from mail.example.com (mail.example.com [203.0.113.4]) by relay for <${EML.email}>; Mon, 3 Mar 2026 09:14:02 +0000`,
    `Subject: Contact ${EML.email}`,
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="dup"',
    "",
    "--dup",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `Write to ${EML.email}.`,
    "",
    "--dup",
    'Content-Type: text/html; charset="utf-8"',
    "",
    `<p>Write to <a href="mailto:${EML.email}">${EML.email}</a>.</p>`,
    "",
    "--dup",
    "Content-Type: application/pdf",
    'Content-Disposition: attachment; filename="contact-john@example.com.pdf"',
    "Content-Transfer-Encoding: base64",
    "",
    "JVBERi0xLjQK",
    "",
    "--dup--",
    "",
  ])
}

/** A multipart whose closing delimiter never arrives. */
export function truncatedMultipartEml(): string {
  return message([
    `From: ${EML.person} <${EML.email}>`,
    "Subject: Cut short",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="cut"',
    "",
    "--cut",
    'Content-Type: text/plain; charset="utf-8"',
    "",
    `The number is ${EML.phone} and then the file ends`,
  ])
}

/** Multiparts inside multiparts, past any reasonable depth. */
export function deeplyNestedEml(levels: number): string {
  const lines: string[] = [
    "From: deep@example.com",
    "Subject: Deep",
    "MIME-Version: 1.0",
  ]

  for (let level = 0; level < levels; level++) {
    lines.push(`Content-Type: multipart/mixed; boundary="b${level}"`)
    lines.push("")
    lines.push(`--b${level}`)
    if (level < levels - 1) continue
    lines.push('Content-Type: text/plain; charset="utf-8"')
    lines.push("")
    lines.push("bottom")
  }

  for (let level = levels - 1; level >= 0; level--) {
    lines.push(`--b${level}--`)
  }

  return message([...lines, ""])
}

/** A message with many small parts, for the part-count limit. */
export function manyPartsEml(parts: number): string {
  const lines: string[] = [
    "From: many@example.com",
    "Subject: Many",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="many"',
    "",
  ]

  for (let index = 0; index < parts; index++) {
    lines.push("--many")
    lines.push('Content-Type: text/plain; charset="utf-8"')
    lines.push("")
    lines.push(`part ${index}`)
    lines.push("")
  }

  lines.push("--many--")
  lines.push("")
  return message(lines)
}

// --- attachments ------------------------------------------------------------

/**
 * Messages built around what is *attached* rather than what is written.
 *
 * These exist for the expansion path, which takes bytes from a stranger and
 * turns them into documents. Every fixture below is a shape somebody can
 * choose: a filename that lies about its contents, a filename that is a path,
 * no filename at all, the same file twice, a message inside a message inside a
 * message. The bytes are real files where the point is that they are read as
 * files, and deliberately not where the point is that they are not.
 */

export type AttachmentSpec = {
  contentType: string
  /** Written as a `filename` parameter; omitted entirely when null. */
  filename: string | null
  bytes: Uint8Array
  /** `inline` plus a Content-ID, for a part the HTML body points at. */
  contentId?: string
  /** Overrides the `filename` parameter with a raw parameter string. */
  rawParameters?: string
}

function base64Lines(bytes: Uint8Array): string[] {
  const encoded = Buffer.from(bytes).toString("base64")
  const lines: string[] = []
  for (let index = 0; index < encoded.length; index += 76) {
    lines.push(encoded.slice(index, index + 76))
  }
  return lines.length > 0 ? lines : [""]
}

function attachmentPart(spec: AttachmentSpec): string[] {
  const disposition = spec.contentId ? "inline" : "attachment"
  const parameters =
    spec.rawParameters ??
    (spec.filename === null ? "" : `; filename="${spec.filename}"`)

  return [
    `Content-Type: ${spec.contentType}`,
    `Content-Disposition: ${disposition}${parameters}`,
    ...(spec.contentId ? [`Content-ID: <${spec.contentId}>`] : []),
    "Content-Transfer-Encoding: base64",
    "",
    ...base64Lines(spec.bytes),
    "",
  ]
}

/** A message with a text body and whatever attachments you hand it. */
export function attachedEml(
  attachments: AttachmentSpec[],
  options: { html?: string } = {}
): string {
  const lines = [
    `From: ${EML.person} <${EML.email}>`,
    `To: <${EML.colleagueEmail}>`,
    "Subject: Your documents",
    "MIME-Version: 1.0",
    'Content-Type: multipart/mixed; boundary="outer"',
    "",
    "--outer",
    `Content-Type: text/${options.html ? "html" : "plain"}; charset="utf-8"`,
    "",
    options.html ?? `Attached is the review for ${EML.person}.`,
    "",
  ]

  for (const attachment of attachments) {
    lines.push("--outer", ...attachmentPart(attachment))
  }

  lines.push("--outer--", "")
  return lines.join("\r\n")
}

/** A message whose HTML body renders an image carried as an inline part. */
export function inlineImageEml(png: Uint8Array): string {
  return attachedEml(
    [
      {
        contentType: "image/png",
        filename: "signature.png",
        bytes: png,
        contentId: "sig@example.com",
      },
    ],
    {
      html: `<p>Regards, ${EML.person}</p><p><img src="cid:sig@example.com"></p>`,
    }
  )
}

/** Bytes that are not a format Anonify reads, so they are carried through. */
export function unreadableBytes(): Uint8Array {
  // A zip whose entries name none of the OOXML part trees: an archive, and
  // nothing more specific.
  return new Uint8Array([
    0x50, 0x4b, 0x03, 0x04, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0x21,
    0x21, 0x21, 0x00, 0x00,
  ])
}
