/**
 * Trimmed copies of real public model-list responses, fetched 2026-09-23 from
 * https://ai-gateway.vercel.sh/v1/models and https://api.deepinfra.com/models/list.
 * Real rows rather than hand-written ones, so the parsers are tested against
 * the shapes the providers actually publish — tiers, regional prices and all.
 */

export const GATEWAY_MODELS = {
  object: "list",
  data: [
    {
      id: "anthropic/claude-haiku-4.5",
      object: "model",
      created: 1755815280,
      released: 1760486400,
      owned_by: "anthropic",
      name: "Claude Haiku 4.5",
      context_window: 200000,
      max_tokens: 64000,
      type: "language",
      zdr: "all",
      no_training: "all",
      tags: [
        "explicit-caching",
        "file-input",
        "reasoning",
        "tool-use",
        "vision",
        "web-search",
        "structured-output",
      ],
      regions: ["eu", "us"],
      supported_specifications: ["v2", "v3", "v4"],
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      supported_parameters: [
        "max_tokens",
        "temperature",
        "stop",
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
      temperature: true,
      reasoning_options: [
        {
          type: "toggle",
        },
        {
          type: "budget_tokens",
          min: 1024,
        },
      ],
      knowledge: "2025-02-28",
      interleaved: true,
      pricing: {
        input: "0.000001",
        output: "0.000005",
        input_cache_read: "0.0000001",
        input_cache_write: "0.00000125",
        web_search: "10",
        regional: {
          eu: {
            input: "0.0000011",
            output: "0.0000055",
            input_cache_read: "0.00000011",
            input_cache_write: "0.000001375",
          },
          us: {
            input: "0.0000011",
            output: "0.0000055",
            input_cache_read: "0.00000011",
            input_cache_write: "0.000001375",
          },
        },
      },
    },
    {
      id: "google/gemini-2.5-pro",
      object: "model",
      created: 1755815280,
      released: 1742428800,
      owned_by: "google",
      name: "Gemini 2.5 Pro",
      context_window: 1048576,
      max_tokens: 65535,
      type: "language",
      zdr: "some",
      no_training: "all",
      tags: [
        "file-input",
        "reasoning",
        "tool-use",
        "vision",
        "web-search",
        "implicit-caching",
        "structured-output",
      ],
      regions: ["eu", "us"],
      supported_specifications: ["v2", "v3", "v4"],
      modalities: {
        input: ["text", "image", "pdf"],
        output: ["text"],
      },
      supported_parameters: [
        "max_tokens",
        "temperature",
        "stop",
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
      temperature: true,
      reasoning_options: [
        {
          type: "toggle",
        },
        {
          type: "effort",
          values: ["none", "low", "medium", "high"],
        },
        {
          type: "budget_tokens",
        },
      ],
      knowledge: "2025-01",
      pricing: {
        input: "0.00000125",
        input_tiers: [
          {
            cost: "0.00000125",
            min: 0,
            max: 200001,
          },
          {
            cost: "0.0000025",
            min: 200001,
          },
        ],
        output: "0.00001",
        output_tiers: [
          {
            cost: "0.00001",
            min: 0,
            max: 200001,
          },
          {
            cost: "0.000015",
            min: 200001,
          },
        ],
        input_cache_read: "0.000000125",
        input_cache_read_tiers: [
          {
            cost: "0.000000125",
            min: 0,
            max: 200001,
          },
          {
            cost: "0.00000025",
            min: 200001,
          },
        ],
        web_search: "35",
        maps_search: "25",
        service_tiers: {
          priority: {
            input: "0.00000225",
            output: "0.000018",
            input_cache_read: "0.000000225",
            long_context: {
              threshold: 200001,
              input: "0.0000045",
              output: "0.000027",
              input_cache_read: "0.00000045",
            },
          },
          flex: {
            input: "0.000000625",
            output: "0.000005",
            long_context: {
              threshold: 200001,
              input: "0.00000125",
              output: "0.0000075",
            },
          },
        },
        regional: {
          eu: {
            input: "0.00000125",
            input_tiers: [
              {
                cost: "0.00000125",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.0000025",
                min: 200001,
              },
            ],
            output: "0.00001",
            output_tiers: [
              {
                cost: "0.00001",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.000015",
                min: 200001,
              },
            ],
            input_cache_read: "0.000000125",
            input_cache_read_tiers: [
              {
                cost: "0.000000125",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.00000025",
                min: 200001,
              },
            ],
          },
          us: {
            input: "0.00000125",
            input_tiers: [
              {
                cost: "0.00000125",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.0000025",
                min: 200001,
              },
            ],
            output: "0.00001",
            output_tiers: [
              {
                cost: "0.00001",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.000015",
                min: 200001,
              },
            ],
            input_cache_read: "0.000000125",
            input_cache_read_tiers: [
              {
                cost: "0.000000125",
                min: 0,
                max: 200001,
              },
              {
                cost: "0.00000025",
                min: 200001,
              },
            ],
          },
        },
      },
    },
    {
      id: "alibaba/qwen-3-32b",
      object: "model",
      created: 1755815280,
      released: 1745798400,
      owned_by: "alibaba",
      name: "Qwen 3 32B",
      context_window: 128000,
      max_tokens: 8192,
      type: "language",
      zdr: "all",
      no_training: "all",
      tags: ["reasoning", "tool-use", "structured-output"],
      supported_specifications: ["v2", "v3", "v4"],
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      supported_parameters: [
        "max_tokens",
        "temperature",
        "stop",
        "tools",
        "tool_choice",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
      temperature: true,
      reasoning_options: [
        {
          type: "toggle",
        },
        {
          type: "budget_tokens",
          min: 1,
          max: 38912,
        },
      ],
      knowledge: "2025-04",
      pricing: {
        input: "0.00000016",
        output: "0.00000064",
        varies_by_provider: true,
      },
    },
    {
      id: "alibaba/qwen3-embedding-0.6b",
      object: "model",
      created: 1755815280,
      released: 1763078400,
      owned_by: "alibaba",
      name: "Qwen3 Embedding 0.6B",
      context_window: 32768,
      max_tokens: 32768,
      type: "embedding",
      zdr: "all",
      no_training: "all",
      supported_specifications: ["v2", "v3", "v4"],
      modalities: {
        input: ["text"],
        output: ["text"],
      },
      pricing: {
        input: "0.00000001",
      },
    },
    {
      id: "perplexity/sonar",
      object: "model",
      created: 1755815280,
      released: 1739923200,
      owned_by: "perplexity",
      name: "Sonar",
      context_window: 127000,
      max_tokens: 8000,
      type: "language",
      zdr: "none",
      no_training: "all",
      tags: ["vision", "web-search", "structured-output"],
      supported_specifications: ["v2", "v3", "v4"],
      modalities: {
        input: ["text", "image"],
        output: ["text"],
      },
      supported_parameters: [
        "max_tokens",
        "temperature",
        "stop",
        "response_format",
        "structured_outputs",
      ],
      temperature: true,
      knowledge: "2025-02",
      pricing: {},
    },
  ],
}

export const DEEPINFRA_MODELS = [
  {
    model_name: "Qwen/Qwen3.8-2.4T-A95B",
    type: "text-generation",
    reported_type: "text-generation",
    tags: [
      "openai",
      "cc-native",
      "tools",
      "json",
      "structured-output",
      "reasoning",
      "featured",
    ],
    pricing: {
      discount: null,
      discount_ends_at: null,
      short: null,
      full: null,
      table: null,
      type: "tokens",
      cents_per_input_token: 0.0002,
      cents_per_output_token: 0.0006,
      rate_per_input_token_cached: 0.1,
      rate_per_input_token_cache_write: null,
      rate_per_service_tier_priority: null,
      rate_per_service_tier_flex: null,
      rate_per_explicit_cache_write_token: null,
      explicit_cache_granularity_tokens: null,
    },
    max_tokens: 262144,
    replaced_by: null,
    deprecated: null,
    quantization: "fp4",
    mmlu: null,
    expected: null,
    create_ts: "2026-08-12T18:24:34+00:00",
    private: 0,
    is_partner: false,
  },
  {
    model_name: "zai-org/GLM-4.7",
    type: "text-generation",
    reported_type: "text-generation",
    tags: [
      "json",
      "can-disable-reasoning",
      "openai",
      "structured-output",
      "tools",
      "reasoning",
      "flex",
    ],
    pricing: {
      discount: null,
      discount_ends_at: null,
      short: null,
      full: null,
      table: null,
      type: "tokens",
      cents_per_input_token: 0.00004,
      cents_per_output_token: 0.000175,
      rate_per_input_token_cached: 0.2,
      rate_per_input_token_cache_write: null,
      rate_per_service_tier_priority: null,
      rate_per_service_tier_flex: 0.8,
      rate_per_explicit_cache_write_token: null,
      explicit_cache_granularity_tokens: null,
    },
    max_tokens: 202752,
    replaced_by: null,
    deprecated: null,
    quantization: "fp4",
    mmlu: null,
    expected: null,
    create_ts: "2025-12-23T02:20:26+00:00",
    private: 0,
    is_partner: false,
  },
  {
    model_name: "run-diffusion/Juggernaut-Flux",
    type: "text-to-image",
    reported_type: "text-to-image",
    tags: [],
    pricing: {
      discount: null,
      discount_ends_at: null,
      short: null,
      full: null,
      table: null,
      type: "image_units",
      cents_per_image_unit: 0.9,
      default_width: 1024,
      default_height: 1024,
      default_iterations: 25,
      default_price_cents: null,
      usage_from_cost: false,
    },
    max_tokens: null,
    replaced_by: "black-forest-labs/FLUX-1-dev",
    deprecated: 1751283332,
    quantization: null,
    mmlu: null,
    expected: null,
    create_ts: "2025-03-18T12:09:32+00:00",
    private: 0,
    is_partner: false,
  },
]
