/**
 * Reading and writing `.env`, as a thing on its own.
 *
 * Split out of `scripts/setup.ts` because one of these functions decides
 * whether somebody keeps their documents. `pnpm setup` offers to reuse the
 * secrets already in a `.env` rather than generating new ones, and that offer
 * is only as good as `parseEnv`: a line it fails to recognise is a value it
 * silently drops, and the value most likely to be dropped that way is
 * `ENCRYPTION_KEY` — which is not a password to be rotated. Documents are
 * sealed with per-document keys wrapped by it, so replacing it does not reset
 * anything; it makes everything already stored permanently unreadable.
 *
 * A script that runs `main()` on import cannot be tested, so the parts worth
 * testing live here instead. `tests/env-file.test.ts` is the reason.
 */

import { parse } from "dotenv"

export type EnvLine = {
  key: string
  value: string
  comment?: string
  /**
   * Written as `# KEY=value`.
   *
   * How a default is recorded. The line is inert, so the code's own default
   * stays in force, and the file still says what that default is — which is
   * the difference between "unset" and "unset, and here is what that means".
   */
  commented?: boolean
}

export type EnvGroup = {
  heading: string
  note?: string[]
  lines: EnvLine[]
}

/** How far a commented default is padded before its trailing explanation. */
const COMMENT_COLUMN = 52

export function renderEnv(title: string, groups: EnvGroup[]): string {
  const out: string[] = [
    `# ${title}`,
    "# Generated by `pnpm setup`. Safe to edit by hand.",
    "#",
    "# Commented-out lines are this instance's defaults, written down rather",
    "# than left to be discovered. Uncomment one to change it.",
    "",
  ]

  for (const group of groups) {
    if (group.lines.length === 0) continue

    out.push(
      `# ---- ${group.heading} ${"-".repeat(Math.max(0, 60 - group.heading.length))}`
    )
    for (const line of group.note ?? []) out.push(`# ${line}`)
    if (group.note) out.push("#")

    for (const line of group.lines) {
      // A live value gets its explanation above it, where it is read before the
      // value. An inert default gets it alongside, so a block of twenty
      // defaults stays a block rather than forty alternating lines.
      if (line.comment && !line.commented) out.push(`# ${line.comment}`)

      const assignment = `${line.commented ? "# " : ""}${line.key}=${quoteEnvValue(line.value)}`
      out.push(
        line.comment && line.commented
          ? `${assignment.padEnd(COMMENT_COLUMN)} # ${line.comment}`
          : assignment
      )
    }
    out.push("")
  }

  return out.join("\n")
}

/**
 * An existing `.env`, as a map.
 *
 * Deliberately forgiving about what it reads — `export FOO=bar`, quoted
 * values, blank lines, indentation, CRLF — because this is used to *keep*
 * values somebody set, and failing to recognise one means throwing it away.
 * Commented lines are skipped, which is what makes the defaults this script
 * writes inert on a re-run rather than being read back as choices.
 */
export function parseEnv(source: string): Map<string, string> {
  return new Map(Object.entries(parse(source)))
}

function quoteEnvValue(value: string): string {
  if (!/[\s#'"`]/.test(value)) return value
  for (const quote of ["'", '"', "`"]) {
    if (!value.includes(quote)) return `${quote}${value}${quote}`
  }
  throw new Error(
    "An environment value contains an unsupported combination of quotes"
  )
}

/**
 * Whether a stored secret is still usable.
 *
 * Both secrets have to decode to 32 bytes, so a truncated or half-pasted one is
 * caught here rather than at the first document. Reusing a dud would be worse
 * than generating a fresh one: it fails at runtime, after the instance looks
 * configured.
 */
export function decodesTo32Bytes(value: string): boolean {
  if (!value) return false
  if (/^[0-9a-fA-F]{64}$/.test(value)) return true

  // Buffer.from is lenient with base64 — it skips what it cannot read rather
  // than throwing — so the length of what came back is the real check.
  return Buffer.from(value, "base64").length === 32
}
