/**
 * Interactive setup.
 *
 *   pnpm setup
 *
 * Writes a working `.env` for one of two ways of running Anonify, and says
 * plainly which values still need a key. The alternative — a list of
 * environment variables in a README and a runtime failure when one is missing —
 * is how a fresh clone becomes an afternoon.
 *
 * Nothing here is required: `.env.example` documents every variable, and this
 * script only saves people from discovering them one error at a time.
 */

import { randomBytes } from "node:crypto"
import { existsSync } from "node:fs"
import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { createInterface } from "node:readline/promises"

const ENV_PATH = path.join(process.cwd(), ".env")

type Mode = "local" | "demo"

/** 32 bytes of hex — what the crypto and identity layers expect. */
function secret(): string {
  return randomBytes(32).toString("hex")
}

type EnvLines = { key: string; value: string; comment?: string }[]

function render(title: string, groups: { heading: string; lines: EnvLines }[]): string {
  const out: string[] = [
    `# ${title}`,
    "# Generated by `pnpm setup`. Safe to edit by hand.",
    "",
  ]

  for (const group of groups) {
    out.push(`# ---- ${group.heading} ${"-".repeat(Math.max(0, 60 - group.heading.length))}`)
    for (const line of group.lines) {
      if (line.comment) out.push(`# ${line.comment}`)
      out.push(`${line.key}=${line.value}`)
    }
    out.push("")
  }

  return out.join("\n")
}

function localEnv(): string {
  return render("Anonify — fully local", [
    {
      heading: "Runtime profile",
      lines: [
        {
          key: "ANONIFY_PROFILE",
          value: "self-hosted",
          comment: "Generous rate limits. `pnpm rate-limit show` to inspect.",
        },
      ],
    },
    {
      heading: "Database (docker compose)",
      lines: [
        {
          key: "DATABASE_URL",
          value: "postgresql://anonify:anonify@localhost:5432/anonify",
        },
        {
          key: "DATABASE_DRIVER",
          value: "postgres",
          comment: "Neon's serverless driver is only for Neon.",
        },
      ],
    },
    {
      heading: "Object storage (MinIO, via docker compose)",
      lines: [
        { key: "STORAGE_DRIVER", value: "s3" },
        { key: "S3_ENDPOINT", value: "http://localhost:9000" },
        { key: "S3_BUCKET", value: "anonify" },
        { key: "S3_REGION", value: "us-east-1" },
        { key: "S3_ACCESS_KEY_ID", value: "anonify" },
        { key: "S3_SECRET_ACCESS_KEY", value: "anonify-dev-secret" },
        { key: "S3_FORCE_PATH_STYLE", value: "true" },
      ],
    },
    {
      heading: "OCR",
      lines: [
        {
          key: "OCR_PROVIDER",
          value: "tesseract",
          comment: "Runs locally. No account, no API key.",
        },
      ],
    },
    {
      heading: "Secrets (generated — keep them)",
      lines: [
        {
          key: "ENCRYPTION_KEY",
          value: secret(),
          comment: "Master key for per-document AES-256-GCM. Losing it loses stored documents.",
        },
        { key: "FINGERPRINT_SECRET", value: secret() },
      ],
    },
    {
      heading: "Scheduled cleanup",
      lines: [
        {
          key: "CRON_SECRET",
          value: secret(),
          comment:
            "Gates the expiry sweep. The container runs as production, where the endpoint requires it.",
        },
      ],
    },
    {
      heading: "Optional",
      lines: [
        {
          key: "AI_GATEWAY_API_KEY",
          value: "",
          comment: "Without it, pattern detection and manual redaction still work.",
        },
        { key: "AI_MODEL", value: "" },
      ],
    },
  ])
}

function demoEnv(): string {
  return render("Anonify — demo-compatible", [
    {
      heading: "Runtime profile",
      lines: [
        {
          // The profile describes who can reach the instance, not which
          // services it uses. This branch picks Neon and Vercel Blob; it is
          // still your instance, so it gets your allowances. Setting "demo"
          // here meant an ordinary spreadsheet failed to process against a
          // quota sized for a shared anonymous endpoint.
          key: "ANONIFY_PROFILE",
          value: "self-hosted",
          comment:
            'Set to "demo" only if this deployment is public and shared: ' +
            "strict rate limits and small daily quotas.",
        },
      ],
    },
    {
      heading: "Database — Neon (https://neon.tech)",
      lines: [
        {
          key: "DATABASE_URL",
          value: "",
          comment: "REQUIRED. The pooled connection string.",
        },
      ],
    },
    {
      heading: "Object storage — Vercel Blob",
      lines: [
        {
          key: "BLOB_READ_WRITE_TOKEN",
          value: "",
          comment: "REQUIRED. From the Vercel dashboard, Storage tab.",
        },
      ],
    },
    {
      heading: "OCR — Mistral (https://console.mistral.ai)",
      lines: [
        { key: "OCR_PROVIDER", value: "mistral" },
        {
          key: "MISTRAL_API_KEY",
          value: "",
          comment: "REQUIRED for OCR. Or set OCR_PROVIDER=tesseract to run it locally.",
        },
      ],
    },
    {
      heading: "AI Gateway",
      lines: [
        {
          key: "AI_GATEWAY_API_KEY",
          value: "",
          comment: "Optional. Without it the contextual detection pass is skipped.",
        },
        { key: "AI_MODEL", value: "" },
      ],
    },
    {
      heading: "Secrets (generated — keep them)",
      lines: [
        { key: "ENCRYPTION_KEY", value: secret() },
        { key: "FINGERPRINT_SECRET", value: secret() },
      ],
    },
    {
      heading: "Scheduled cleanup",
      lines: [
        {
          key: "CRON_SECRET",
          value: secret(),
          comment: "Gates the expiry sweep. Set the same value in your host's cron config.",
        },
      ],
    },
  ])
}

const NEXT_STEPS: Record<Mode, string[]> = {
  local: [
    "docker compose up -d      # Postgres + MinIO, with the bucket created",
    "pnpm db:migrate           # apply the schema",
    "pnpm ocr:warm             # fetch the ~5 MB OCR model now, not mid-redaction",
    "pnpm dev                  # http://localhost:3000",
  ],
  demo: [
    "Fill in DATABASE_URL, BLOB_READ_WRITE_TOKEN and MISTRAL_API_KEY in .env",
    "pnpm db:migrate           # apply the schema to your Neon database",
    "pnpm dev                  # http://localhost:3000",
  ],
}

async function main(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout })

  try {
    console.log(`
  Anonify setup

  How would you like to run Anonify?

    1. Fully local          (recommended for development)
       Postgres and MinIO through Docker Compose, Tesseract for OCR.
       No accounts, no API keys, nothing leaves your machine.

    2. Demo-compatible
       The same services as the deployed demo: Neon, Vercel Blob and
       Mistral OCR. You provide your own keys.
`)

    const answer = (await rl.question("  Choose 1 or 2 [1]: ")).trim()
    const mode: Mode = answer === "2" ? "demo" : "local"

    if (existsSync(ENV_PATH)) {
      const existing = await readFile(ENV_PATH, "utf8")
      const hasValues = existing
        .split("\n")
        .some((line) => /^[A-Z_]+=.+/.test(line.trim()))

      if (hasValues) {
        console.log("\n  A .env already exists and has values in it.")
        const overwrite = (
          await rl.question("  Overwrite it? Existing secrets will be lost. [y/N]: ")
        )
          .trim()
          .toLowerCase()

        if (overwrite !== "y" && overwrite !== "yes") {
          console.log("\n  Left .env alone. Nothing was changed.\n")
          return
        }

        // Keep a copy: ENCRYPTION_KEY is not recoverable, and documents sealed
        // with the old one cannot be read without it.
        await writeFile(`${ENV_PATH}.backup`, existing, "utf8")
        console.log("  Previous .env copied to .env.backup")
      }
    }

    await writeFile(ENV_PATH, mode === "local" ? localEnv() : demoEnv(), "utf8")

    console.log(`
  Wrote .env for the ${mode === "local" ? "fully local" : "demo-compatible"} setup.
`)

    if (mode === "demo") {
      console.log("  Still needed — the script cannot generate these:\n")
      console.log("    DATABASE_URL           a Neon connection string")
      console.log("    BLOB_READ_WRITE_TOKEN  a Vercel Blob token")
      console.log("    MISTRAL_API_KEY        for OCR (or use OCR_PROVIDER=tesseract)\n")
    }

    console.log("  Next:\n")
    for (const step of NEXT_STEPS[mode]) console.log(`    ${step}`)
    console.log("\n  See README.md for the full walkthrough.\n")
  } finally {
    rl.close()
  }
}

main().catch((error: unknown) => {
  console.error(`\n  ${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
